#[".powerlevel10k"]
#	type = "git-repo"
#	url = "https://github.com/romkatv/powerlevel10k.git"
#	refreshPeriod = "168h"

[".tmux/plugins/tpm"]
	type = "git-repo"
	url = "https://github.com/tmux-plugins/tpm"
	refreshPeriod = "168h"

["~/bin/fzf"]
	type = "archive"
	url = "https://github.com/junegunn/fzf/releases/download/v0.55.0/fzf-0.55.0-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
	extract = "true"
	stripComponents = 1
