#[".powerlevel10k"]
#	type = "git-repo"
#	url = "https://github.com/romkatv/powerlevel10k.git"
#	refreshPeriod = "168h"

[".tmux/plugins/tpm"]
	type = "git-repo"
	url = "https://github.com/tmux-plugins/tpm"
	refreshPeriod = "168h"
